name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "src/Radarr.Api.*/openapi.json"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "src/NzbDrone.Core/Localization/Core/**"
      - "src/Radarr.Api.*/openapi.json"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FRAMEWORK: net8.0
  RAW_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  RADARR_MAJOR_VERSION: 5
  VERSION: 5.27.0

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.variables.outputs.branch }}
      version: ${{ steps.variables.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Setup Node.js (Volta)
        uses: volta-cli/action@v4

      - name: Setup Variables
        id: variables
        shell: bash
        run: |
          RADARR_VERSION="${{ env.VERSION }}.${{ github.run_number }}"
          echo "RADARR_VERSION=$RADARR_VERSION" >> "$GITHUB_ENV"
          echo "BRANCH=${RAW_BRANCH_NAME//\//-}" >> "$GITHUB_ENV"
          echo "branch=${RAW_BRANCH_NAME//\//-}" >> "$GITHUB_OUTPUT"
          echo "version=$RADARR_VERSION" >> "$GITHUB_OUTPUT"

      - name: Yarn Install
        run: yarn install

      - name: Lint UI
        run: yarn lint

      - name: Build UI & Backend (linux-x64)
        run: ./build.sh --backend --frontend --packages -f net8.0 -r linux-x64
        env:
          RADARR_VERSION: ${{ env.RADARR_VERSION }}
          BRANCH: ${{ env.BRANCH }}

      - name: Upload UI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_ui
          path: _output/UI/**/*

      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_linux
          path: _output/linux-*/**/*

      - name: Publish linux-x64 Test Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tests-linux-x64
          path: _tests/net8.0/linux-x64/publish/**/*

  unit_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Download Test Artifact
        uses: actions/download-artifact@v4
        with:
          name: tests-linux-x64
          path: _tests

      - name: Run All Unit Tests
        run: dotnet test ./_tests/Radarr.*.Test.dll --filter "TestCategory!=ManualTest&TestCategory!=IntegrationTest&TestCategory!=AutomationTest" --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"

  unit_test_postgres:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        postgres: [14, 15]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: radarr
          POSTGRES_USER: radarr
          POSTGRES_DB: radarr
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U radarr" --health-interval=10s
          --health-timeout=5s --health-retries=5
    env:
      Radarr__Postgres__Host: localhost
      Radarr__Postgres__Port: 5432
      Radarr__Postgres__User: radarr
      Radarr__Postgres__Password: radarr
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Download Test Artifact
        uses: actions/download-artifact@v4
        with:
          name: tests-linux-x64
          path: _tests

      - name: Run All Unit Tests (Postgres)
        run: dotnet test ./_tests/Radarr.*.Test.dll --filter "TestCategory!=ManualTest&TestCategory!=IntegrationTest&TestCategory!=AutomationTest" --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"

  integration_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Download Test Artifact
        uses: actions/download-artifact@v4
        with:
          name: tests-linux-x64
          path: _tests

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build_linux
          path: _output

      - name: Setup Bin Directory
        run: |
          mkdir -p _tests/bin
          cp -r ./_output/linux-x64/${{ env.FRAMEWORK }}/Radarr/. _tests/bin/

      - name: Run Integration Tests
        run: dotnet test ./_tests/Radarr.Integration.Test.dll --filter "TestCategory!=ManualTest" --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"

  integration_test_postgres:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        postgres: [14, 15]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: radarr
          POSTGRES_USER: radarr
          POSTGRES_DB: radarr
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U radarr" --health-interval=10s
          --health-timeout=5s --health-retries=5
    env:
      Radarr__Postgres__Host: localhost
      Radarr__Postgres__Port: 5432
      Radarr__Postgres__User: radarr
      Radarr__Postgres__Password: radarr
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Download Test Artifact
        uses: actions/download-artifact@v4
        with:
          name: tests-linux-x64
          path: _tests

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build_linux
          path: _output

      - name: Setup Bin Directory
        run: |
          mkdir -p _tests/bin
          cp -r ./_output/linux-x64/${{ env.FRAMEWORK }}/Radarr/. _tests/bin/

      - name: Run Integration Tests (Postgres)
        run: dotnet test ./_tests/Radarr.Integration.Test.dll --filter "TestCategory!=ManualTest" --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"

  automation_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Download Test Artifact
        uses: actions/download-artifact@v4
        with:
          name: tests-linux-x64
          path: _tests

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build_linux
          path: _output

      - name: Setup Bin Directory
        run: |
          mkdir -p _tests/bin
          cp -r ./_output/linux-x64/${{ env.FRAMEWORK }}/Radarr/. _tests/bin/

      - name: Run Automation Tests
        run: dotnet test ./_tests/Radarr.Automation.Test.dll --filter "TestCategory!=ManualTest" --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"
